version: '2'
services:
  unifi:
    image: linuxserver/unifi:latest
    container_name: unifi
    mem_limit: 4g
    volumes:
      - /opt/docker/unifi/config:/config:rw
    ports:
      - 3478:3478/udp
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8443:8443/tcp
      - 8843:8843/tcp
      - 8880:8880/tcp
    restart: always
    networks:
      - haus
networks:
  haus:
    external:
      name: haus
