version: '2'
services:
  unifi:
    image: jacobalberty/unifi:latest
    container_name: unifi
    mem_limit: 4g
    environment:
      - RUNAS_UID0=false
      - TZ=America/Los_Angeles
      - UNIFI_UID=911
      - UNIFI_GID=911
    volumes:
      - /opt/docker/unifi/config:/unifi:rw
    ports:
      - 3478:3478/udp
      - 6789:6789/tcp
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8443:8443/tcp
      - 8843:8843/tcp
      - 8880:8880/tcp
      - 10001:10001/udp
    restart: always
    networks:
      - haus
networks:
  haus:
    external:
      name: haus
