version: "3"
services:
  nord:
    image: bubuntux/nordvpn
    container_name: nord
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    env_file:
      - /etc/default/ph/nord
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nord_proxy
    ports:
      - 8112:8112/tcp
      - 58846:58846/tcp
    links:
      - nord:deluge
    volumes:
      - /opt/docker/nord-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=115
      - PGID=119
      - UMASK_SET=022
      - TZ=America/Los_Angeles
    volumes:
      - /opt/docker/deluge/config:/config
      - /park_media:/park_media
    restart: unless-stopped
    network_mode: "service:nord"
