version: '3'
services:
  unifi:
    image: linuxserver/unifi:latest
    container_name: unifi
    volumes:
      - /puppy/docker/unifi/config:/config:rw
    ports:
      - 3478:3478/udp
      - 8843:8843/tcp
      - 8880:8880/tcp
    restart: always
    networks:
      - haus
networks:
  haus:
    external:
      name: haus
